feat(i-373): create support for Immutable
couchbaselabs/node-ottoman pull request #397
Opened 2021-02-12 14:34 UTC by gsi-ariam

2021-02-12 15:08 UTC, gsi-chao requested changes

2021-02-12 15:08 UTC, gsi-chao commented on __test__/schema-inmutable.spec.ts
> +    const CardSchema = new Schema(CardSchemaBase, { strict: 'throw' });
What is strict: "throw" strict is a boolean field, Maybe you want to use strategy: CAST_STRATEGY. THROW

2021-02-12 15:08 UTC, gsi-chao commented on src/model/create-model.ts
> +      const schemaData = cast(data, schema, { strategy, strict: !!strict, skip });
You have the wrong concept of strict. Review the documentation in this section https://v2.ottomanjs.com/guides/schema.html#cast-method

2021-02-12 15:08 UTC, gsi-chao commented on src/model/document.ts
> +      if (!this.immutableHasOwnProperty(key) && isImmutable && strict) {
Check the strict logic here too.

2021-02-12 15:08 UTC, gsi-chao commented on src/schema/interfaces/schema.types.ts
> +  strict?: boolean | 'throw';
Review this too.

2021-02-12 15:08 UTC, gsi-chao commented on src/schema/schema.ts
> +    const strict = !!options?.strict || false;
Review this too.

2021-02-12 15:08 UTC, gsi-chao commented on src/schema/schema.ts
> +      strict: options.strict !== undefined ? !!options.strict : !!this.options.strict,
Review this too.

2021-02-16 13:44 UTC, gsi-chao approved these changes
Looks good for me

2021-02-16 19:29 UTC, gsi-alejandro approved these changes

2021-02-16 19:53 UTC, httpJunkie approved these changes

2021-02-16 19:54 UTC, merged